config/routes.rb
Rails.application.routes.draw do
  root                     'landing_pages#home'#, defaults: { :format => "js"}, :remote => :true
  get    'home'      =>    'landing_pages#home', defaults: { :format => "js"}, :remote => :true
  get    'login'     =>    'sessions#new', defaults: { :format => "js"}, :remote => :true
  post   'login'     =>    'sessions#create', defaults: { :format => "js"}, :remote => :true
  get    'extlogin'  =>    'landing_pages#home', :extlogin => :true
  post   'extlogin'  =>    'sessions#create', defaults: { :format => "js"}, :remote => :true
  get    'signup'    =>    'subjects#new', defaults: { :format => "js"}, :remote => :true
  get    'extsignup' =>    'landing_pages#home', :extsignup => :true
  delete 'logout'    =>    'sessions#destroy', defaults: { :format => "js"}, :remote => :true

  get    'about'     =>    'static_pages#about', defaults: { format: 'js'}, remote: :true
  get    'contacts'  =>    'static_pages#contacts', defaults: { format: 'js'}, remote: :true
  get    'help'      =>    'static_pages#help', defaults: { format: 'js'}, remote: :true
  get    'privacy'   =>    'static_pages#privacy', defaults: { format: 'js'}, remote: :true
  get    'terms'     =>    'static_pages#terms', defaults: { format: 'js'}, remote: :true

#  get    'password_resets/new'
#  get    'password_resets/edit.

  post    'accept'   =>      'cookielaws#accept', defaults: { format: 'js'}, remote: :true
  post    'refuse'   =>      'cookielaws#refuse', defaults: { format: 'js'}, remote: :true
  post    'privacy'  =>      'cookielaws#privacy', defaults: { format: 'js'}, remote: :true
  resources :mail_collectors,                    defaults: { format: 'js'}, remote: :true
  resources :jdebugs

#  resources :account_activations, only: [:edit], defaults: { format: 'js'}, remote: :true
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update], defaults: { format: 'js'}, remote: :true

  resources :subjects,            constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true,  except: [:destroy, :show]
  resources :subjects,                                             defaults: { format: 'js'}, remote: :true,  only: [:show, :create]

# administrative resources

  resources :forms,               constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :languages,           constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :social_networks,     constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true,  except: [:destroy, :show]

  resources :posts,               constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :groups,              constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true,  except: [:show]

  resources :landing_pages,       constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true,  except: [:destroy]
  resources :tags,                constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :tests,               constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :images,              constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :media_managers,      constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :subject_profiles,    constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :post_comments,       constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :discussions,         constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :discussion_comments, constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true, except: [:new]

  get       'groups/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'groups#list', :as => :groups_list, defaults: { format: 'js'}, remote: :true
  get       'group/:id/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>    'groups#list_one', :as => :group_list, defaults: { format: 'js'}, remote: :true
  get       'groups/:id(/:filter)'                                      =>    'groups#show', :as => :groups_show, defaults: { format: 'js'}, remote: :true

  get       'social_networks/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'social_networks#list', :as => :social_networks_list, defaults: { format: 'js'}, remote: :true
  get       'social_network/:id/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'social_networks#list_one', :as => :social_network_list, defaults: { format: 'js'}, remote: :true

  get       'subjects/list/:class/:object_id/:rel(/:from_page(/:limit(/:subject(/:deep))))'  =>   'subjects#list', :as => :subjects_list, defaults: { format: 'js'}, remote: :true

  get       'discussions/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'discussions#list', :as => :discussions_list, defaults: { format: 'js'}, remote: :true
  get       'discussions/add(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'discussions#add', :as => :discussions_add, defaults: { format: 'js'}, remote: :true

  get       'posts/list/:social_uuid(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'posts#list', :as => :posts_list, defaults: { format: 'js'}, remote: :true
  get       'post/:id/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>    'posts#list_one', :as => :post_list, defaults: { format: 'js'}, remote: :true


  get       'discussion_comment/new(/:parent_class/:parent_uuid)'            =>    'discussion_comments#new', :as => :new_discussion_comment, defaults: { format: 'js'}, remote: :true

#  get       'post/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'post#list', :as => :posts_list, defaults: { format: 'js'}, remote: :true

# These new routes support passing the belongs_to object

#  post       'discussions/create/:belongs_to_class/:belongs_to_id'          =>   'discussions#create',         :as => :discussions_create, defaults: { format: 'js'}, remote: :true
#  post       'discussion_comments/create/:belongs_to_class/:belongs_to_id'  =>   'discussion_comments#create', :as => :discussion_comment_create, defaults: { format: 'js'}, remote: :true
#  post       'post_comments/create/:belongs_to_class/:belongs_to_id'        =>   'post_comments#create',       :as => :post_comment_create, defaults: { format: 'js'}, remote: :true

# These are miscellaneous routes

  post      'likes/:id/:class/:relationship' =>    'likes#edit',           :as => :onerel, defaults: { format: 'js'}, constraints: AuthConstraint.new, remote: :true
  get       'likes'                          =>    'likes#dummy',          :as => :dummy, constraints: AuthConstraint.new
  get       'searches'                       =>    'likes#search',         :as => :searches, constraints: AuthConstraint.new
#  post      'show_image/:img'                =>    'likes#show_image',     :as => :show_image, defaults: { format: 'js'}, constraints: AuthConstraint.new, remote: :true
#  post      'show_document/:doc'             =>    'likes#show_document',  :as => :show_document, defaults: { format: 'js'}, constraints: AuthConstraint.new, remote: :true
#  post      'show_content/:img'              =>    'likes#show_content',   :as => :show_content, defaults: { format: 'js'}, constraints: AuthConstraint.new, remote: :true
  post      'show_image/:img'                =>    'likes#show_image',     :as => :show_image, defaults: { format: 'js'}, remote: :true
  post      'show_document/:doc'             =>    'likes#show_document',  :as => :show_document, defaults: { format: 'js'}, remote: :true
  post      'show_content/:img'              =>    'likes#show_content',   :as => :show_content, defaults: { format: 'js'}, remote: :true
  get       'hide(/:id)'                     =>    'likes#hide',           :as => :hide, defaults: { format: 'js'}, remote: :true
  get       '/media_managers/list/'          =>    'media_managers#list',  :as => :image_list #, defaults: { format: 'js'}, remote: :true
 # get       'user_profiles'                 =>    'user_profiles#edit',    :as => :edit, constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true

end

app/models/subject_profile.rb
class SubjectProfile 
  include Neo4j::ActiveNode
#  include Uuid
  include CreatedAtUpdatedAt

  property :background_color, type: String, default: 'inherit'
  property :text_color,       type: String, default: 'inherit'
  property :description,      type: String

  has_one  :in, :belongs_to, rel_class: :HasSubjectProfile
  has_one  :out, :has_image, rel_class: :HasImage

  after_create :set_default

  private

  def set_default
    self.background_color = 'inherit' if background_color.nil?
    self.text_color = 'inherit' if text_color.nil?
  end
end

app/controllers/subject_profiles_controller.rb
class SubjectProfilesController < ApplicationController
  include SubjectProfilesHelper
  before_action :check_social_network
  before_action :set_subject_profile, only: [:show, :edit, :update, :destroy]
  respond_to :js

  # GET /subject_profiles/1/show
  def show
    splat(@subject_profile, 'subject_profiles_controller:show')
    jpl_parms = SubjectProfilesHelper.show(@subject_profile)
    render 'forms/show', format: :js, locals: {jpl_parms: jpl_parms, parms: params}
  end

  # GET /subject_profiles/1/edit
  def edit
    splat(@subject_profile, 'subject_profiles_controller:edit')
    jpl_parms = SubjectProfilesHelper.edit_s_sp_i(@subject_profile)
    render 'forms/edit', format: :js, locals: {jpl_parms: jpl_parms, parms: params}
  end

  # PATCH/PUT /subject_profiles/1
  # PATCH/PUT /subject_profiles/1.json
  def update
    splat(subject_profile_params, 'subject_profiles_controller:update')
    begin
      tx = Neo4j::Transaction.new
      @subject_profile.update(subject_profile_params)
    rescue => e
      tx.failure
    ensure
      tx.close
    end

    jpl_parms = SubjectProfilesHelper.update(@subject_profile)
    render 'forms/update', format: :js, locals: {jpl_parms: jpl_parms, parms: params}
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subject_profile
    @subject_profile = SubjectProfile.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def subject_profile_params
    # params[:subject_profile]
    params.require(:subject_profile).permit(:id, :uuid, :description, :background_color, :text_color)
  end

#  def show_edit
#    splat(params, 'subject_profiles_controller:show_edit')##
#
#    @subject_profile = SubjectProfile.find_by(id: params[:id])
#    evline = "SubjectProfilesHelper.#{params[:action]}_s_sp_i(@subject_profile)"
#    jpl_parms = eval evline
#    splat(jpl_parms, 'edit_s_sp_i')
#    jpl_parms
#    render "forms/show", format: :js, locals: {jpl_parms: jpl_parms, parms: params}
#  end
end

app/helpers/subject_profiles_helper.rb
module SubjectProfilesHelper
  def self.show(subject_profile) 
    subject = subject_profile.belongs_to
    image = subject_profile.has_image
    image = Image.new if image.nil?

    h = {
      :subject_profile => {
        :subject_profile => subject_profile,
        :subject => subject,
        :image => image
        }
      } 
  end

  def self.update(subject_profile) 
    self.show(subject_profile)
  end

  def self.edit_s_sp_i(subject_profile) 
    #debugger
    subject = subject_profile.belongs_to
    image = subject_profile.has_image
    image = Image.new if image.nil?

    h = {
      :subject_profile => {
        :subject_profile => subject_profile,
        :subject => subject,
        :image => image
      },
      :image => {
        :image => image,
        :owner => subject_profile,
        :cloudinary => {
          :preset => "subject_photo",
          :page_header => I18n.translate('subject_profile.view.photo.header', operation: I18n.t('operation.edit'), full_name: subject.full_name ), 
          :folder => "subject/#{subject.uuid}"
        },
        :connections => [{
          :from => subject_profile,
          :rel_name => :has_image,
          :rel_revname => :is_image_of,
          :rel_object => :image,
          :to => :self,
          :history => :true
        }]
      }
    } 
  end
end

app/views/subject_profiles/_edit.html.haml
-# ############################ SUBJECT PROFILE EDIT #######################################
- _uuid = subject_profile.uuid
%div{ id: "edit-#{_uuid}" }

  = render partial: 'forms/header', locals: { style: 'current', title: translate('subject_profile.view.header', operation: t('operation.edit'), full_name: subject.full_name )}
  
  = bootstrap_form_for(subject_profile, :remote => :true ) do |f|

    = f.hidden_field :uuid, value: subject_profile.uuid

    .nothing= f.text_area :description, prepend: t('attribute.description'), placeholder: t('subject_profile.view.description'), hide_label: :true
    .spacer

    .nothing= f.color_field :background_color, prepend: t('attribute.background_color'), placeholder: t('subject_profile.view.background_color'), hide_label: :true, class: 'left-align' 
    .spacer

    .nothing= f.color_field :text_color, prepend: t('attribute.text_color'), placeholder: t('subject_profile.view.text_color'), hide_label: :true, class: 'left-align'
    .spacer

    = render partial: 'forms/footer', locals: { style: 'current' }

app/views/subject_profiles/_photo_load.html.haml
- "Upload subject photo"

#upload_subject_photo
	= render partial: "subject_profiles/photo_show", locals: { :subject_profile => subject_profile, :size => :standard }

- ratio_logo = 1.0
- button_caption = t("subject_profile.view.photo_button_caption")
- photo_folder_name = build_object_image_path( { :photo => nil } )

#upload_subject_photo1
	:javascript 
		cloudinary.applyUploadWidget(document.getElementById('upload_subject_photo1'), 
		{ cloud_name: "#{cloudinary_name?}", 
		stylesheet: document.baseURI+'/assets/cloudinary.css', theme: "default",
		button_class: 'joinple-button',
		cropping: 'server', multiple: 'false', 
		cropping_aspect_ratio: "#{ratio_logo}", 
		cropping_default_selection_ratio: "1", 
		button_caption: "#{button_caption}",
		upload_preset: 'subject-photo', 
		field_name: 'subject_profile[photo]', 
		folder: "#{photo_folder_name}", 
		min_image_width: "300", min_image_height: "300" },
			function(error, result) {console.log(error, result)});

app/views/subject_profiles/_photo_show.html.haml
- sizes = Hash.new
- sizes = { basic: 18, small: 24, comment: 30, header: 32, btn: 36, thumb: 84, icon: 128, standard: 200, profile: 250 }

- size = :btn unless size.is_a? Symbol

- dimension = sizes[size]

- aShape = defined?(shape) ? shape : "" 

- quality = 50
- if dimension < 200  
	- quality = 20

= cl_image_tag image_uuid, width: dimension, crop: :scale, quality: quality, class: "#{aShape}", default_image: 'default_avatar.png'

app/views/subject_profiles/_show.html.haml
-# subject_profile = object
-# logger.debug 'subject_profiles/_show.html.haml'
-# subject = subject_profile.belongs_to
= render partial: 'forms/header', locals: { style: 'current', f_uuid: f_uuid, title: translate('subject_profile.view.header', operation: '', full_name: subject.full_name) }
-#.page-thumbnail{ style: "color: #{subject_profile.text_color}; background-color: #{subject_profile.background_color}; " }
  = translate('subject_profile.view.header', operation: '', full_name: subject.full_name)
.subject-profile{ id: subject_profile.uuid }
  = render partial: 'subjects/owner', locals: { subject_profile: subject_profile, size: :thumb, special: :true }
  = "#{subject.full_name} (@#{subject.nickname})"
  - unless subject_profile.description.nil?
    .border-1
      = "#{subject_profile.description}"
  = render partial: 'forms/modify', locals: { object: subject_profile }
-#
  .border-1
  - if can_modify?(subject_profile)
    .command-line-m
      = link_to edit_subject_profile_path(subject_profile), remote: :true, hide_label: :true, 'data-placement': :top, title: 'Modify the element' do
        %i.im-pencil
      = link_to subject_profile, method: :delete, data: { confirm: 'Are you sure?' }, remote: :true, hide_label: :true, 'data-placement': :top, title: 'Delete the element' do
        %i.im-bin