config/routes.rb
Rails.application.routes.draw do
  root                     'landing_pages#home'#, defaults: { :format => "js"}, :remote => :true
  get    'home'      =>    'landing_pages#home', defaults: { :format => "js"}, :remote => :true
  get    'login'     =>    'sessions#new', defaults: { :format => "js"}, :remote => :true
  post   'login'     =>    'sessions#create', defaults: { :format => "js"}, :remote => :true
  get    'extlogin'  =>    'landing_pages#home', :extlogin => :true
  post   'extlogin'  =>    'sessions#create', defaults: { :format => "js"}, :remote => :true
  get    'signup'    =>    'subjects#new', defaults: { :format => "js"}, :remote => :true
  get    'extsignup' =>    'landing_pages#home', :extsignup => :true
  delete 'logout'    =>    'sessions#destroy', defaults: { :format => "js"}, :remote => :true

  get    'about'     =>    'static_pages#about', defaults: { format: 'js'}, remote: :true
  get    'contacts'  =>    'static_pages#contacts', defaults: { format: 'js'}, remote: :true
  get    'help'      =>    'static_pages#help', defaults: { format: 'js'}, remote: :true
  get    'privacy'   =>    'static_pages#privacy', defaults: { format: 'js'}, remote: :true
  get    'terms'     =>    'static_pages#terms', defaults: { format: 'js'}, remote: :true

#  get    'password_resets/new'
#  get    'password_resets/edit.

  post    'accept'   =>      'cookielaws#accept', defaults: { format: 'js'}, remote: :true
  post    'refuse'   =>      'cookielaws#refuse', defaults: { format: 'js'}, remote: :true
  post    'privacy'  =>      'cookielaws#privacy', defaults: { format: 'js'}, remote: :true
  resources :mail_collectors,                    defaults: { format: 'js'}, remote: :true
  resources :jdebugs

#  resources :account_activations, only: [:edit], defaults: { format: 'js'}, remote: :true
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update], defaults: { format: 'js'}, remote: :true

  resources :subjects,            constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true,  except: [:destroy, :show]
  resources :subjects,                                             defaults: { format: 'js'}, remote: :true,  only: [:show, :create]

# administrative resources

  resources :forms,               constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :languages,           constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :social_networks,     constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true,  except: [:destroy, :show]

  resources :posts,               constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :groups,              constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true,  except: [:show]

  resources :landing_pages,       constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true,  except: [:destroy]
  resources :tags,                constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :tests,               constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :images,              constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :media_managers,      constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :subject_profiles,    constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :post_comments,       constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :discussions,         constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :discussion_comments, constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true, except: [:new]

  get       'groups/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'groups#list', :as => :groups_list, defaults: { format: 'js'}, remote: :true
  get       'group/:id/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>    'groups#list_one', :as => :group_list, defaults: { format: 'js'}, remote: :true
  get       'groups/:id(/:filter)'                                      =>    'groups#show', :as => :groups_show, defaults: { format: 'js'}, remote: :true

  get       'social_networks/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'social_networks#list', :as => :social_networks_list, defaults: { format: 'js'}, remote: :true
  get       'social_network/:id/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'social_networks#list_one', :as => :social_network_list, defaults: { format: 'js'}, remote: :true

  get       'subjects/list/:class/:object_id/:rel(/:from_page(/:limit(/:subject(/:deep))))'  =>   'subjects#list', :as => :subjects_list, defaults: { format: 'js'}, remote: :true

  get       'discussions/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'discussions#list', :as => :discussions_list, defaults: { format: 'js'}, remote: :true
  get       'discussions/add(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'discussions#add', :as => :discussions_add, defaults: { format: 'js'}, remote: :true

  get       'posts/list/:social_uuid(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'posts#list', :as => :posts_list, defaults: { format: 'js'}, remote: :true
  get       'post/:id/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>    'posts#list_one', :as => :post_list, defaults: { format: 'js'}, remote: :true


  get       'discussion_comment/new(/:parent_class/:parent_uuid)'            =>    'discussion_comments#new', :as => :new_discussion_comment, defaults: { format: 'js'}, remote: :true

#  get       'post/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'post#list', :as => :posts_list, defaults: { format: 'js'}, remote: :true

# These new routes support passing the belongs_to object

#  post       'discussions/create/:belongs_to_class/:belongs_to_id'          =>   'discussions#create',         :as => :discussions_create, defaults: { format: 'js'}, remote: :true
#  post       'discussion_comments/create/:belongs_to_class/:belongs_to_id'  =>   'discussion_comments#create', :as => :discussion_comment_create, defaults: { format: 'js'}, remote: :true
#  post       'post_comments/create/:belongs_to_class/:belongs_to_id'        =>   'post_comments#create',       :as => :post_comment_create, defaults: { format: 'js'}, remote: :true

# These are miscellaneous routes

  post      'likes/:id/:class/:relationship' =>    'likes#edit',           :as => :onerel, defaults: { format: 'js'}, constraints: AuthConstraint.new, remote: :true
  get       'likes'                          =>    'likes#dummy',          :as => :dummy, constraints: AuthConstraint.new
  get       'searches'                       =>    'likes#search',         :as => :searches, constraints: AuthConstraint.new
#  post      'show_image/:img'                =>    'likes#show_image',     :as => :show_image, defaults: { format: 'js'}, constraints: AuthConstraint.new, remote: :true
#  post      'show_document/:doc'             =>    'likes#show_document',  :as => :show_document, defaults: { format: 'js'}, constraints: AuthConstraint.new, remote: :true
#  post      'show_content/:img'              =>    'likes#show_content',   :as => :show_content, defaults: { format: 'js'}, constraints: AuthConstraint.new, remote: :true
  post      'show_image/:img'                =>    'likes#show_image',     :as => :show_image, defaults: { format: 'js'}, remote: :true
  post      'show_document/:doc'             =>    'likes#show_document',  :as => :show_document, defaults: { format: 'js'}, remote: :true
  post      'show_content/:img'              =>    'likes#show_content',   :as => :show_content, defaults: { format: 'js'}, remote: :true
  get       'hide(/:id)'                     =>    'likes#hide',           :as => :hide, defaults: { format: 'js'}, remote: :true
  get       '/media_managers/list/'          =>    'media_managers#list',  :as => :image_list #, defaults: { format: 'js'}, remote: :true
 # get       'user_profiles'                 =>    'user_profiles#edit',    :as => :edit, constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true

end

app/views/shared/_chats.html.haml
%li.nav-header
  %span
    My chats
    %span.pull-right{"data-toggle" => "collapse", "data-target" => ".row_chat"} X
  %ul#test.nav.nav-list.collapse.in
    %li
      %span 
        %a{:href => "/ticket_list.cfm", :title => "Show list of tickets"} My administrated chats
    %li
      %span 
        %a{:href => "/account/", :title => "Edit user accounts"} Join a chat
    %li
      %span 
        %a{:href => "/account/", :title => "Edit user accounts"} chat 1
    %li
      %span 
        %a{:href => "/account/", :title => "Edit user accounts"} chat 2
    %li
      %span 
        %a{:href => "/account/", :title => "Edit user accounts"} chat 3

app/views/shared/_common_panel_footer.html.haml
%button.icon_only.joinple-button-base{ type: 'submit', name: 'commit', hide_label: :true, title: t('button.hint.save') }
  %i.im-check
  = t('button.save')
%button.icon_only.joinple-button-base{ type: 'reset', name: 'reset', hide_label: :true, title: t('button.hint.clear') } 
  %i.im-eraser
  = t('button.clear')  

app/views/shared/_common_panel_header.html.haml
-#****************************************************************************************************************
  - sample: render partial: 'shared/common_panel_heading', locals: { :style => "your style", :data_target => "your target", :title => "your title"}
  - Needs three params:
    - style: a String usually one of
      - "current" for current_social_network_style
      - "super" super_social_network_style
      - or a different style that will be passed as a block
    - data-target: the toggler to be used 
      - example: "#group-form"
    - title
  ****************************************************************************************************************
- decoded_style = case style                              |
    when "current"  then current_social_network_style     | 
    when "super"    then super_social_network_style       |
    else                 style                            |
  end      

-#.panel-heading{ :style => decoded_style }
  .float-right{ :style => "padding-top: 10px; padding-right: 10px; "}
    = link_to hide_path("#{uuid}"), :remote => :true, :title => t("button.exit") do
      .panel-title
        - if defined?(title)
          = title
        - else
          - raise "TITLE MISSED"
        %i.im-uncheck.to-right{ :style => "color: #ffffff;"}

- title = defined?(title) ? title : "Add"
- decoded_style = case style                              |
    when "current"  then  current_social_network_style    | 
    when "super" then super_social_network_style          |
    else style                                            |
  end                                   
.panel-heading{ :style => decoded_style }
  %a.toggle{ :type => "toggle", "data-target" => data_target, "data-toggle" => "collapse"}
    .panel-title
      - if defined?(title)
        = title
        -#.button.close{:type => "button", "data-dismiss" => "alert", "aria-label" => "Close" }
      - else
        - raise "TITLE MISSED"
      %i.im-uncheck.to-right{ :style => "color: #ffffff;"}
      -#%span.im-stack.to-right
        %i.im-uncheck-stack-1
        %i.im-uncheck-stack-2

app/views/shared/_error_messages.html.haml
-# unless object.nil?
  - object.methods.each do |e|
    = e
  - if object.errors.any?
    #error_explanation
      .alert.alert-danger
        The form contains #{pluralize(@obj.errors.count, "error")}.
      %ul
        - @obj.errors.full_messages.each do |msg|
          %li= msg

app/views/shared/_group.html.haml
.row.nomargin{ :id => "#{group.uuid}" }
  .thumbnail
    .container-fluid.nopadding
      -# owner = post.is_owned_by
      - owner = group.query_as(:p).match("(p)<-[r:owns]-(u:User)").pluck(:u).first
      = puts "Owner: #{owner} --------------------------------------------------------"
      %aside.col-xs-1.nomargin
        .post-owner
          = gravatar_for owner, size: 32
          = link_to root_path do
            %span.glyphicons.icon-triangle-up
          = rand(0...1000)
          %br
          = link_to root_path do
            %span.glyphicons.icon-triangle-down
      .col-xs-9
        .post-header
          = " - by #{owner.full_name} - #{group.created_at.strftime('%F at %H:%M')}"
        .post-title
          = group.title
        .post-content
          = group.description
        .post-glyps
          = link_to onerel_path(group,'Group','likes'), :method => :post, :remote => :true do
            %span.glyphicons.icon-like-1
            - likes = group.query_as(:p).match("(p)<-[r:likes]-(u:User)").pluck(:u).count
            - if likes > 0
              %span.badge
                = likes
          -#  Like
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          = link_to root_path do
            %span.glyphicons.icon-share-outline
          -#  Join
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          = link_to root_path do
            %span.glyphicons.icon-star-4
          -#  Preferite

app/views/shared/_menu_discussions.html.haml
= link_to discussions_list_path("allingroupsiparticipate"), :remote => :true do
  %li.left.list-group-item.no-padding{ :style => current_social_network_style }
    = t("layout.view.left.discussions")
= link_to dummy_path, :remote => :true do
  %li.left.list-group-item.no-padding
    %i.im-dot
    Discussion 1
= link_to dummy_path, :remote => :true do
  %li.left.list-group-item.no-padding
    %i.im-dot
    Discussion 2
= link_to dummy_path, :remote => :true do
  %li.left.list-group-item.no-padding
    %i.im-dot
    Discussion 3

app/views/shared/_menu_groups.html.haml
= link_to groups_list_path("iparticipate"), :remote => :true do
  %li.left.list-group-item.no-padding{ :style => current_social_network_style }
    = t("layout.view.left.groups")
= link_to dummy_path, :remote => :true do
  %li.left.list-group-item.no-padding
    %i.im-dot
    Group 1
= link_to dummy_path, :remote => :true do
  %li.left.list-group-item.no-padding
    %i.im-dot
    Group 2
= link_to dummy_path, :remote => :true do
  %li.left.list-group-item.no-padding
    %i.im-dot
    Group 3

app/views/shared/_menu_pages.html.haml
= link_to dummy_path, :remote => :true do
  %li.left.list-group-item.no-padding{ :style => current_social_network_style }
    Pages
= link_to dummy_path, :remote => :true do
  %li.left.list-group-item.no-padding
    %i.im-dot
    Page 1
= link_to dummy_path, :remote => :true do
  %li.left.list-group-item.no-padding
    %i.im-dot
    Page 2
= link_to dummy_path, :remote => :true do
  %li.left.list-group-item.no-padding
    %i.im-dot
    Page 3

app/views/shared/_menu_preferites.html.haml
= link_to dummy_path, :remote => :true do
  %li.left.list-group-item.no-padding{ :style => current_social_network_style }
    = t("layout.view.left.preferites")
= link_to dummy_path, :remote => :true do
  %li.left.list-group-item.no-padding
    %i.im-dot
    Preferite 1
= link_to dummy_path, :remote => :true do
  %li.left.list-group-item.no-padding
    %i.im-dot
    Preferite 2
= link_to dummy_path, :remote => :true do
  %li.left.list-group-item.no-padding
    %i.im-dot
    Preferite 3

app/views/shared/_people.html.haml
#post-header-right.shadowing
	- subjects = Subject.all
	- (1..1).each do |a|
		- subjects.each do |subject|
			%span.subject-faces
				= link_to subject_profile_path(subject.has_profile.uuid), :remote => :true, :title => "#{subject.first_name} #{subject.last_name} (@#{subject.nickname})" do
					= render partial: 'subjects/owner', locals: { subject: subject, size: :basic, special: :true }

app/views/shared/_preferites.html.haml
.section
  %ul.list-group.title
    %li.list-group-item
      %span.glyphicons.icon-star-4
      Preferites
    %li.list-group-item
      %a{ :role => "menuitem", :href => "/ticket_list.cfm" }
        %span.glyphicons.glyphicons-tag
        Preferred 1
    %li.list-group-item
      %a{ :role => "menuitem", :href => "/ticket_list.cfm" }
        %span.glyphicons.icon-dot.transparent
        Preferred  2
    %li.list-group-item
      %a{ :role => "menuitem", :href => "/ticket_list.cfm" }
        %span.glyphicons.glyphicons-tag
        Preferred  3
    %li.list-group-item
      %a{ :role => "menuitem", :href => "/ticket_list.cfm" }
        %span.glyphicons.glyphicons-tag
        Preferred  4

app/views/shared/_social_networks.html.haml
%h1 Discussions
%h3 Start a new discussion
= form_for Post.new do |f|
  = render 'shared/error_messages', object: f.object
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Publish'
#posts_grid
  - @posts.each do |post|
    = render partial:'shared/post', object: post

app/views/shared/_user.html.haml
.row.nomargin.col-sm-6.col-md-4{ :id => "#{user.uuid}" }
  .thumbnail
    .container-fluid.nopadding
      .user-owner
        = link_to user_path(user.uuid), :remote => :true do
          = gravatar_for user, size: 128
      .user
        = "#{user.full_name}"
      .post-title
        =# user.title
      .post-content
        =# user.content
      .post-glyps
        = link_to onerel_path(user,'User','likes'), :method => :user, :remote => :true do
          %span.glyphicons.icon-like-1
          - likes = user.query_as(:p).match("(p)<-[r:likes]-(u:User)").pluck(:u).count
          - if likes > 0
            %span.badge
              = likes
        -#  Like

app/views/shared/index.js.erb
$("#main-header").html("<%= escape_javascript(render partial: "'#{class_name.downcase}/header'", locals: { "'#{class_name.downcase.pluralize}'": '@"#{class_name.downcase.pluralize}"''} ) %>" );
$("#main-add").html("<%= escape_javascript(render partial: 'form', locals: { language: Language.new } ) %>" );
$("#main-content").html("<%= escape_javascript(render partial: 'index', locals: { languages: @languages} ) %>" );