config/routes.rb
Rails.application.routes.draw do
  root                     'landing_pages#home'#, defaults: { :format => "js"}, :remote => :true
  get    'home'      =>    'landing_pages#home', defaults: { :format => "js"}, :remote => :true
  get    'login'     =>    'sessions#new', defaults: { :format => "js"}, :remote => :true
  post   'login'     =>    'sessions#create', defaults: { :format => "js"}, :remote => :true
  get    'extlogin'  =>    'landing_pages#home', :extlogin => :true
  post   'extlogin'  =>    'sessions#create', defaults: { :format => "js"}, :remote => :true
  get    'signup'    =>    'subjects#new', defaults: { :format => "js"}, :remote => :true
  get    'extsignup' =>    'landing_pages#home', :extsignup => :true
  delete 'logout'    =>    'sessions#destroy', defaults: { :format => "js"}, :remote => :true

  get    'about'     =>    'static_pages#about', defaults: { format: 'js'}, remote: :true
  get    'contacts'  =>    'static_pages#contacts', defaults: { format: 'js'}, remote: :true
  get    'help'      =>    'static_pages#help', defaults: { format: 'js'}, remote: :true
  get    'privacy'   =>    'static_pages#privacy', defaults: { format: 'js'}, remote: :true
  get    'terms'     =>    'static_pages#terms', defaults: { format: 'js'}, remote: :true

#  get    'password_resets/new'
#  get    'password_resets/edit.

  post    'accept'   =>      'cookielaws#accept', defaults: { format: 'js'}, remote: :true
  post    'refuse'   =>      'cookielaws#refuse', defaults: { format: 'js'}, remote: :true
  post    'privacy'  =>      'cookielaws#privacy', defaults: { format: 'js'}, remote: :true
  resources :mail_collectors,                    defaults: { format: 'js'}, remote: :true
  resources :jdebugs

#  resources :account_activations, only: [:edit], defaults: { format: 'js'}, remote: :true
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update], defaults: { format: 'js'}, remote: :true

  resources :subjects,            constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true,  except: [:destroy, :show]
  resources :subjects,                                             defaults: { format: 'js'}, remote: :true,  only: [:show, :create]

# administrative resources

  resources :forms,               constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :languages,           constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :social_networks,     constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true,  except: [:destroy, :show]

  resources :posts,               constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :groups,              constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true,  except: [:show]

  resources :landing_pages,       constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true,  except: [:destroy]
  resources :tags,                constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :tests,               constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :images,              constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :media_managers,      constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :subject_profiles,    constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :post_comments,       constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :discussions,         constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true
  resources :discussion_comments, constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true, except: [:new]

  get       'groups/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'groups#list', :as => :groups_list, defaults: { format: 'js'}, remote: :true
  get       'group/:id/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>    'groups#list_one', :as => :group_list, defaults: { format: 'js'}, remote: :true
  get       'groups/:id(/:filter)'                                      =>    'groups#show', :as => :groups_show, defaults: { format: 'js'}, remote: :true

  get       'social_networks/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'social_networks#list', :as => :social_networks_list, defaults: { format: 'js'}, remote: :true
  get       'social_network/:id/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'social_networks#list_one', :as => :social_network_list, defaults: { format: 'js'}, remote: :true

  get       'subjects/list/:class/:object_id/:rel(/:from_page(/:limit(/:subject(/:deep))))'  =>   'subjects#list', :as => :subjects_list, defaults: { format: 'js'}, remote: :true

  get       'discussions/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'discussions#list', :as => :discussions_list, defaults: { format: 'js'}, remote: :true
  get       'discussions/add(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'discussions#add', :as => :discussions_add, defaults: { format: 'js'}, remote: :true

  get       'posts/list/:social_uuid(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'posts#list', :as => :posts_list, defaults: { format: 'js'}, remote: :true
  get       'post/:id/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>    'posts#list_one', :as => :post_list, defaults: { format: 'js'}, remote: :true


  get       'discussion_comment/new(/:parent_class/:parent_uuid)'            =>    'discussion_comments#new', :as => :new_discussion_comment, defaults: { format: 'js'}, remote: :true

#  get       'post/list(/:filter(/:from_page(/:limit(/:subject(/:deep)))))'  =>   'post#list', :as => :posts_list, defaults: { format: 'js'}, remote: :true

# These new routes support passing the belongs_to object

#  post       'discussions/create/:belongs_to_class/:belongs_to_id'          =>   'discussions#create',         :as => :discussions_create, defaults: { format: 'js'}, remote: :true
#  post       'discussion_comments/create/:belongs_to_class/:belongs_to_id'  =>   'discussion_comments#create', :as => :discussion_comment_create, defaults: { format: 'js'}, remote: :true
#  post       'post_comments/create/:belongs_to_class/:belongs_to_id'        =>   'post_comments#create',       :as => :post_comment_create, defaults: { format: 'js'}, remote: :true

# These are miscellaneous routes

  post      'likes/:id/:class/:relationship' =>    'likes#edit',           :as => :onerel, defaults: { format: 'js'}, constraints: AuthConstraint.new, remote: :true
  get       'likes'                          =>    'likes#dummy',          :as => :dummy, constraints: AuthConstraint.new
  get       'searches'                       =>    'likes#search',         :as => :searches, constraints: AuthConstraint.new
#  post      'show_image/:img'                =>    'likes#show_image',     :as => :show_image, defaults: { format: 'js'}, constraints: AuthConstraint.new, remote: :true
#  post      'show_document/:doc'             =>    'likes#show_document',  :as => :show_document, defaults: { format: 'js'}, constraints: AuthConstraint.new, remote: :true
#  post      'show_content/:img'              =>    'likes#show_content',   :as => :show_content, defaults: { format: 'js'}, constraints: AuthConstraint.new, remote: :true
  post      'show_image/:img'                =>    'likes#show_image',     :as => :show_image, defaults: { format: 'js'}, remote: :true
  post      'show_document/:doc'             =>    'likes#show_document',  :as => :show_document, defaults: { format: 'js'}, remote: :true
  post      'show_content/:img'              =>    'likes#show_content',   :as => :show_content, defaults: { format: 'js'}, remote: :true
  get       'hide(/:id)'                     =>    'likes#hide',           :as => :hide, defaults: { format: 'js'}, remote: :true
  get       '/media_managers/list/'          =>    'media_managers#list',  :as => :image_list #, defaults: { format: 'js'}, remote: :true
 # get       'user_profiles'                 =>    'user_profiles#edit',    :as => :edit, constraints: AuthConstraint.new, defaults: { format: 'js'}, remote: :true

end

app/models/subject.rb
class Subject
  include Neo4j::ActiveNode
 # include Uuid
  include CreatedAtUpdatedAt
  include SecurePassword

  attr_accessor :remember_token
  attr_accessor :activation_token
  attr_accessor :reset_token

  property :remember_digest,   type:  String
  property :activation_digest, type:  String
  property :activated,         type:  Boolean, default: false
  property :activated_at,      type:  DateTime
  property :reset_digest,      type:  String
  property :reset_sent_at,     type:  DateTime
  property :admin,             type:  Boolean, default: false
 
  # before_update :check_default
  before_create :check_default
  before_save :check_default
  # before_save :set_last_name
  before_create :create_activation_digest
  # debugger
  # before_initialize :create_uuid

  property :nickname,    type:   String
  property :first_name,  type:   String
  property :last_name,   type:   String
  property :email,       type:   String

  has_secure_password
  property :password_digest

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :nickname, presence: :true
  validates_uniqueness_of :nickname, case_sensitive: :false
  validates :first_name, presence: :true
  validates :last_name, presence: :true
  # validates :email, presence: true
  validates :email, format: {with: VALID_EMAIL_REGEX}
  validates_uniqueness_of :email, case_sensitive: :false
  validates :password, length: {minimum: 6}, allow_blank: :true

  # Subject application rels

  has_many  :out, :likes, rel_class: :Likes              # :any
  has_many  :out, :follows, rel_class: :Follows          # :any
  has_many  :in,  :is_followed_by, rel_class: :Follows   # Subject
  has_many  :in,  :use_language, rel_class: :Speaks      # Language
  has_many  :out, :owns, rel_class: :Owns                # :any
  has_many  :out, :is_member_of, rel_class: :MemberOf    # Group
  has_one   :out, :has_profile, rel_class: :HasSubjectProfile # Profile


  # debugger
  # uuid = SecureRandom.uuid if new_record?

  # Remembers a subject in the database for use in persistent sessions.
  def remember
    self.remember_token = new_token
    update_attribute(:remember_digest, digest(remember_token))
  end

  # Forgets a subject.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def check_default
    self.nickname = self.nickname.downcase.gsub(/\s+/, "") if self.nickname
    self.first_name = self.first_name.downcase.titleize.strip.split.join(" ") if self.first_name
    self.last_name = self.last_name.downcase.titleize.strip.split.join(" ") if self.last_name
    self.admin = false if self.admin.nil?
    self.email = self.email.downcase    
  end

  # Returns a random token.
  def new_token
    SecureRandom.urlsafe_base64
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email(request_full_path)
    SubjectMailer.account_activation(self, request_full_path).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = Subject.new_token
    update_attribute(:reset_digest,  Subject.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email
  def send_password_reset_email
    SubjectMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def profile?
    Subject.has_profile
  end

  private

  def create_activation_digest
    self.activation_token = new_token
    self.activation_digest = digest(self.activation_token)
  end

  def digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper

  # Returns the Gravatar for the given subject.
 # def gravatar_for(subject, options = { size: 80 }) 
 #   gravatar_id = Digest::MD5::hexdigest(subject.email.downcase)
 #   size = options[:size]
 #   gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
 #   #gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
 #   image_tag(gravatar_url, alt: subject.full_name, class: "gravatar img-responsive")
 # end

#  def full_name(subject)
#  def Subject.full_name
#    "#{subject.first_name} #{subject.last_name}"
#  end

  

  def Subject.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def Subject.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a subject in the database for use in persistent sessions.
  def remember
    self.remember_token = Subject.new_token
    update_attribute(:remember_digest, Subject.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def activated?
    true
  end

  def followers(uuid)
     Neo4j::Session.query("match (follower:Subject)-[r:follows]->(:Subject { uuid : '#{uuid}'}) return follower")
  end

  def followings(uuid)
     Neo4j::Session.query("match (following:Subject)<-[r:follows]-(:Subject { uuid : '#{uuid}'}) return following")
  end

  def followers_count(uuid)
     x = Neo4j::Session.query("match (follower:Subject)-[r:follows]->(:Subject { uuid : '#{uuid}'}), count(follower) as c return c")
     z=x.next
   end

  def followings_count(uuid)
     x = Neo4j::Session.query("match (following:Subject)<-[r:follows]-(:Subject { uuid : '#{uuid}'}), count(following) as c return c")
     z=x.next
  end

  def is_owner?(owner,object)
     unless owner.nil?
       x = Neo4j::Session.query("match (object:#{object.class.name.singularize} { uuid : '#{object.uuid}'})<-[owns:owns]-(owner:Subject { uuid : '#{owner.uuid}'}) return count(owner) as c")
puts x.next
       z=x.first[:c]
       z == 1
     else
       false
     end
   end

  def is_group_owner?(owner,object)
     unless owner.nil?
        x = Neo4j::Session.query("match (object:#{object.class.name.singularize} { uuid : '#{object.uuid}'})<-[owns:owns]-(owner:Subject { uuid : '#{owner.uuid}'}) return count(owner) as c")
puts x.next
        z=x.first[:c]
        z == 1
      else
        false
      end
   end


  def is_subject_profile?(subject,profile)
     unless profile.nil?
       x = Neo4j::Session.query("match (subject:#{subject.class.name.singularize} { uuid : '#{subject.uuid}'})-[has_profile:has_profile]->(profile:SubjectProfile { uuid : '#{profile.uuid}'}) return count(profile) as c")
puts x.next
       z=x.first[:c]
       z == 1
     else
       false
     end
   end


end

app/views/subjects/_form.html.haml
.col-xs-10
.col-xs-40
  .panel.panel-default
    .panel-heading{ :style => super_social_network_style }
      =t("subject.view.signup.title")
      .panel-title
    .panel-body
      = bootstrap_form_for(subject, :remote => :true, :html => {:multipart => true} ) do |f|
        .nothing= f.text_field :nickname, :prepend => t("subject.model.attribute.nickname"), :placeholder => t("subject.view.signup.placeholder.nickname"), :hide_label => :true
        .spacer
        .nothing= f.text_field :first_name, :prepend => t("subject.model.attribute.first_name"), :placeholder => t("subject.view.signup.placeholder.first_name"), :hide_label => :true
        .spacer
        .nothing= f.text_field :last_name, :prepend => t("subject.model.attribute.last_name"), :placeholder => t("subject.view.signup.placeholder.last_name"), :hide_label => :true
        .spacer
        .nothing= f.text_field :email, :prepend => t("attribute.email"), :placeholder => t("placeholder.email"), :hide_label => :true
        .spacer
        .nothing= f.text_field :password, :prepend => t("attribute.password"), :placeholder => t("placeholder.password"), :hide_label => :true
        .spacer
        .nothing= f.text_field :password_confirmation, :prepend => t("subject.model.attribute.password_confirmation"), :placeholder => t("subject.view.signup.placeholder.password_confirmation"), :hide_label => :true
        .spacer

        %button.btn.btn-default.joinple-button-base{ :type => "submit", :name => "commit", :hide_label => :true, :style => super_social_network_style }
          %i.im-added
          =t("subject.view.signup.create_button")
.col-xs-10

app/views/subjects/_header.html.haml
#subjects-page
  .command-line-container
    .command-line-l
      = link_to subjects_list_path("Subject","x","all"), :remote => :true, :title => "View all subjects" do
        %i.activable.im-all-posts
      = link_to subjects_list_path("Subject","x","ifollowing"), :remote => :true, :title => "View all subjects I follow" do
        %i.activable.im-my-posts
      = link_to subjects_list_path("Subject","x","myfollowers"), :remote => :true, :title => "View all subjects following me" do
        %i.activable.im-bookmark
      = render partial: 'shared/search'

app/views/subjects/_index.html.haml
- if logged_in?
  .page-thumbnail{ :style => super_social_network_style }
    = title
  #grid5.grid-padding.no-padding{ "data-columns" => "" }
    - subjects.each do |subject|
      = render partial: 'subjects/show', locals: { subject: subject }

= javascript_include_tag 'salvattore.min', media: 'all', 'data-turbolinks-track' => true

app/views/subjects/_info.html.haml
- rels = count_relationships(subject) 
- social_network = current_social_network
.row.nothing.top-rounded{ :style => current_social_network_style }
  .col-xs-28.nothing
    = render partial: 'subjects/owner', locals: { subject: subject, size: :thumb, shape: "subject-photo", special: :true }
  .col-xs-32.nothing
    .subject-info
      .name
        = subject.first_name
        %br
        = subject.last_name
      .nick
        = "@#{subject.nickname}"
      .stars{ :style => "color: yellow;" }
        - stars((1 + rand(49)) / 10.0).each do |k|
          %i{ :class => "im-star-#{k}" }

.row.nothing.subject-info.icons
  .col-xs-12.nothing
    %i.activable.im-following
    %br
    - followings_number = rels["out-follows-Subject"]
    = followings_number
  .col-xs-12.nothing
    %i.activable.im-followers
    %br
    - followers_number = rels["in-follows-Subject"]
    = followers_number
  .col-xs-12.nothing
    %i.activable.im-discussions
    %br
    - discu_number = rels["in-follows-Discussion"]
    = discu_number
  .col-xs-12.nothing
    %i.activable.im-groups
    %br
    - groups_number = rels["out-owns-Group"]
    = groups_number
  .col-xs-12.nothing
    %i.activable.im-blog2
    %br
    - blog_number = rels["in-follows-Blog"]
    = blog_number

app/views/subjects/_list.html.haml
- if logged_in?
  .page-thumbnail{ :style => super_social_network_style }
    = title
  #grid4.grid-padding.no-padding{ "data-columns" => "" }
    - objects.each do |subject|
      = render partial: 'subjects/show_short', locals: { subject: subject }

= javascript_include_tag 'salvattore.min', media: 'all', 'data-turbolinks-track' => true

app/views/subjects/_new.html.haml
= render partial: 'subjects/form', locals: { subject: Subject.new }

app/views/subjects/_owner.html.haml
-# debugger
- if defined?(object)
  - logger.debug object.class.name
  - if object.class.name == 'SubjectProfile'
    - subject = object.belongs_to
    - subject_profile = object
  - else
    - subject = object.is_owned_by
    - subject_profile = subject.has_profile
- elsif not subject_profile.nil?
  - subject = subject_profile.belongs_to
- elsif not subject.nil?
  - subject_profile = subject.has_profile
- else
  - object = nil
  - raise "Input requires object or subject_profile or subject)"
-# image = subject_profile.has_image(:i, :r).where('r.type = {photo}').params(photo: 'photo').first(:i)
- image = subject_profile.has_image
- image_uuid = image.nil? ? 'h' : "subject/#{subject.uuid}/#{image.uuid}"
- image_uuid = image.cloudinary_id unless image.nil?

- title = defined?(title) ? title : "Edit"

- size = :thumb unless defined?(size)
- shape = "" if shape.nil?

- if defined?(special)
  = render partial: "subject_profiles/photo_show", locals: { :image_uuid => image_uuid, :size => size, :shape => shape }
- elsif defined?(use_current_subject)
  = render partial: "subject_profiles/photo_show", locals: { :image_uuid => image_uuid, :size => :btn, :shape => "responsive circle" }
- elsif defined?(show)
  = render partial: "subject_profiles/photo_show", locals: { :image_uuid => image_uuid, :size => size, :shape => "responsive circle padding-1" }
- elsif defined?(type)
  %span{ :class => "semi-transparent-#{type}-bar", :style => "clear: both;" }
  %div.solida
    = link_to subject_profile_path(subject_profile.uuid), :remote => :true, :title => title, :shape => ("hoverable white") do
      = render partial: "subject_profiles/photo_show", locals: { :image_uuid => image_uuid, :size => size, :shape => "circle padding-1" }
      %span.vertical-middle= "#{subject.full_name} (@#{subject.nickname})"
    %span.to-right.vertical-middle
      = "created on #{object.created_at.to_formatted_s(:short)}"
- else
  %span
    = link_to subject_profile_path(subject_profile.uuid), :remote => :true, :title => title, :class => ("hoverable") do
      = render partial: "subject_profiles/photo_show", locals: { :image_uuid => image_uuid, :size => :btn, :shape => "circle padding-1" }
      = "#{subject.full_name} (@#{subject.nickname})"

app/views/subjects/_show.html.haml
%div{ :id => subject.uuid }
  - puts subject.full_name
  - rels = count_relationships(subject) 
  - subject_profile = subject.has_profile
  .joinple-contour-2
    .row.nothing.top-rounded
      .col-xs-28.nothing
        = render partial: "subjects/owner", locals: { :subject_profile => subject_profile, :size => :profile }
      .col-xs-32.nothing
        .subject-info.subject-name
          = subject.first_name
          %br
          = subject.last_name
          %br
          %span.subject-info.subjectnick= "@#{subject.nickname}"
          %br
          %span.subject-info.subject-star
            - stars((1 + rand(49)) / 10.0).each do |k|
              %i{ :class => "im-star-#{k}" }
    .border-1
    .row
      .col-xs-12.nothing
        %i.subject-info-icons.im-following
        %br
        - followings_number = rels["out-follows-Subject"]
        = followings_number
      .col-xs-12.nothing
        %i.subject-info-icons.im-followers
        %br
        - followers_number = rels["in-follows-Subject"]
        = followers_number
      .col-xs-12.nothing
        %i.subject-info-icons.im-discussions
        %br
        - discu_number = rels["in-follows-Discussion"]
        = discu_number
      .col-xs-12.nothing
        %i.subject-info-icons.im-groups
        %br
        - groups_number = rels["out-owns-Group"]
        = groups_number
      .col-xs-12.nothing
        %i.subject-info-icons.im-blog2
        %br
        - blog_number = rels["in-follows-Blog"]
        = blog_number
    .border-1
    .centered
      = link_to onerel_path(subject,'Subject','follows'), :method => :post, :remote => :true, :to_class => :true, :class => ("hoverable") do
        - unless current_subject?(subject)
          - i_follow = current_subject.query_as(:p).match("(p)-[r:follows]->(u:Subject { uuid : '#{subject.uuid}' })").pluck(:u).count
          = i_follow == 1 ? "unfollow" : "follow" 
        - else
          &nbsp;
  .spacer









-#  
      .relative.nothing
        = image_tag subject_profile.photo.url(:icon), :class => "responsive centered"
      .content
        .title= subject.full_name
        .subject-nick= "@#{subject.nickname}"
        .spacer
        %span.centered.subject-info.subject-star
          - stars((1 + rand(49)) / 10.0).each do |k|
            %i{ :class => "im-star-#{k}" }
        .border-1
        .row.nothing.subject-info-icons
          .col-xs-12.nothing
            %i.subject-info-icons.im-following
            %br
            - followings_number = rels["out-follows-Subject"]
            = followings_number
          .col-xs-12.nothing
            %i.subject-info-icons.im-followers
            %br
            - followers_number = rels["in-follows-Subject"]
            = followers_number
            = 46532
          .col-xs-12.nothing
            %i.subject-info-icons.im-discussions
            %br
            172
          .col-xs-12.nothing
            %i.subject-info-icons.im-groups
            %br
            - groups_number = rels["out-owns-Group"]
            = groups_number
          .col-xs-12.nothing
            %i.subject-info-icons.im-blog2
            %br
            93
          -#.border-1
            This is and old implementation for like/follow
            .post-glyps
              = link_to onerel_path(subject,'Subject','likes'), :method => :post, :remote => :true do
                %span.glyphicons.icon-like-1
                - likes = subject.query_as(:p).match("(p)<-[r:likes]-(u:Subject)").pluck(:u).count
                %span.badge
                  = likes
        .border-1
        .centered
          = link_to onerel_path(subject,'Subject','follows'), :method => :post, :to_class => :true do
            - unless current_subject?(subject)
              - i_follow = current_subject.query_as(:p).match("(p)-[r:follows]->(u:Subject { uuid : '#{subject.uuid}' })").pluck(:u).count
              = i_follow == 1 ? "unfollow" : "follow" 
            - else
              .transparent-line

      .spacer
    .spacer

app/views/subjects/_show_short.html.haml
%div
  %div{ :id => "ss#{subject.uuid}" }
    .command_line_s.shadowing.rounded{ :style => "background-color: #ffffff;"}
      = link_to subject_profile_path(subject.has_profile.uuid), :remote => :true, :title => "View profile", :class => "hoverable" do
        = image_tag "#{subject.has_profile.photo.url(:btn)}", :name => "subject_profile_#{subject.has_profile.uuid}", :class => "subject-photo"
        = subject.full_name

app/views/subjects/create.js.erb
$("#main-add").html("<%= escape_javascript(render partial: 'form', locals: { subject: @subject } ) %>" );

app/views/subjects/index.js.erb
$("#tech-info").html("<%= escape_javascript(render partial: 'sessions/tech_info') %>" );
$("#main-header").html("<%= escape_javascript(render 'header', locals: { subjects: @subjects} ) %>" );
$("#main-add").html("" );
$("#main-content").html("<%= escape_javascript(render partial: 'index', locals: { subjects: @subjects,  title: "Subjects"} ) %>" );
$("#right-context *").html("");
$("#main-debug").html("<%= escape_javascript(render partial: 'sessions/debug') %>");

app/views/subjects/new.html.haml
= render partial: 'subjects/form', locals: { subject: Subject.new }

app/views/subjects/new.js.erb
$("#page").html("<%= escape_javascript(render partial: 'layouts/c3_9_0' ) %>" );
$("#main-add").html("<%= escape_javascript(render partial: 'form', locals: { subject: @subject } ) %>" );